apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kube-visibility # kpt-set: ${namespace}
resources:
  - ../../upstream/alertmanager
  - service-monitor.yaml
patches:
  - alertmanager-patch.yaml
generatorOptions:
  disableNameSuffixHash: true
secretGenerator:
  - name: alertmanager-visibility-configuration
    behavior: create
    files:
      - ./configuration/alertmanager.yaml
