apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: alertmanager-visibility
  labels:
    name: alertmanager-visibility
    prometheus-visibility.monitoring: "enabled"
spec:
  jobLabel: alertmanager
  namespaceSelector:
    matchNames:
      - kube-visibility # kpt-set: ${namespace}
  selector:
    matchLabels:
      alertmanager: visibility
  endpoints:
    - port: web
      interval: 30s
