apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1 # kpt-set: ${grafana.replicas}
  template:
    spec:
      containers:
        - name: grafana
          resources:
            limits:
              cpu: 100m # kpt-set: ${grafana.resources-limits-cpu}
              memory: 100Mi # kpt-set: ${grafana.resources-limits-memory}
            requests:
              cpu: 50m # kpt-set: ${grafana.resources-requests-cpu}
              memory: 50Mi # kpt-set: ${grafana.resources-requests-memory}
          volumeMounts:
            - name: grafana-configuration
              mountPath: /etc/grafana/grafana.ini
              subPath: grafana.ini
              readOnly: true
            - name: grafana-dashboards-providers
              mountPath: /etc/grafana/provisioning/dashboards
              readOnly: true
            - name: grafana-dashboards-datasources
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: true
            - name: grafana-dashboards-prometheus-0
              mountPath: /grafana/dashboards/prometheus-0
              readOnly: true
            - name: grafana-dashboards-kubernetes-0
              mountPath: /grafana/dashboards/kubernetes-0
              readOnly: true
            - name: grafana-dashboards-kubernetes-1
              mountPath: /grafana/dashboards/kubernetes-1
              readOnly: true
            - name: grafana-dashboards-kubernetes-2
              mountPath: /grafana/dashboards/kubernetes-2
              readOnly: true
            - name: grafana-dashboards-kubernetes-3
              mountPath: /grafana/dashboards/kubernetes-3
              readOnly: true
            - name: grafana-dashboards-kubernetes-4
              mountPath: /grafana/dashboards/kubernetes-4
              readOnly: true
            - name: grafana-dashboards-infrastructure-0
              mountPath: /grafana/dashboards/infrastructure-0
              readOnly: true
            - name: grafana-dashboards-grafana-0
              mountPath: /grafana/dashboards/grafana-0
              readOnly: true
      volumes:
        - name: grafana-configuration
          configMap:
            name: grafana-configuration
        - name: grafana-dashboards-providers
          configMap:
            name: grafana-dashboards-providers
        - name: grafana-dashboards-datasources
          configMap:
            name: grafana-dashboards-datasources
        - name: grafana-dashboards-prometheus-0
          configMap:
            name: grafana-dashboards-prometheus-0
        - name: grafana-dashboards-kubernetes-0
          configMap:
            name: grafana-dashboards-kubernetes-0
        - name: grafana-dashboards-kubernetes-1
          configMap:
            name: grafana-dashboards-kubernetes-1
        - name: grafana-dashboards-kubernetes-2
          configMap:
            name: grafana-dashboards-kubernetes-2
        - name: grafana-dashboards-kubernetes-3
          configMap:
            name: grafana-dashboards-kubernetes-3
        - name: grafana-dashboards-kubernetes-4
          configMap:
            name: grafana-dashboards-kubernetes-4
        - name: grafana-dashboards-infrastructure-0
          configMap:
            name: grafana-dashboards-infrastructure-0
        - name: grafana-dashboards-grafana-0
          configMap:
            name: grafana-dashboards-grafana-0
