apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: alertmanager-alert-rules
  labels:
    prometheus: visibility
    role: alert-rules
spec:
  groups:
    - name: alert--alertmanager
      rules:
        - alert: AlertmanagerConfigInconsistent
          expr: |
            count_values("config_hash", alertmanager_config_hash{service="alertmanager-visibility"}) BY (service) / ON(service) GROUP_LEFT() label_replace(max(prometheus_operator_spec_replicas{job="prometheus-operator",controller="alertmanager"}) by (name, job, namespace, controller), "service", "alertmanager-$1", "name", "(.*)") != 1
          for: 5m
          labels:
            severity: critical
            team: visibility
            service: alertmanager
          annotations:
            title: "Alertmanager instance is out of sync"
            summary: "The Alertmanager instance {{ $labels.service }} is out of sync"
            description: "The configuration of the instances of the Alertmanager cluster {{$labels.service}} are out of sync."
        - alert: AlertmanagerFailedReload
          expr: |
            alertmanager_config_last_reload_successful{service="alertmanager-visibility"} == 0
          for: 10m
          labels:
            severity: warning
            team: visibility
            service: alertmanager
          annotations:
            title: "Reloading Alertmanager's configuration has failed"
            summary: "Reloading Alertmanager's configuration has failed for {{ $labels.service}}."
            description: "Reloading Alertmanager's configuration has failed for {{ $labels.namespace}}/{{ $labels.pod}}."
        - alert: AlertmanagerMembersInconsistent
          expr: |
            alertmanager_cluster_members{service="alertmanager-visibility"}
              != on (service) GROUP_LEFT()
            count by (service) (alertmanager_cluster_members{service="alertmanager-visibility"})
          for: 5m
          labels:
            severity: critical
            team: visibility
            service: alertmanager
          annotations:
            title: "Alertmanager members inconsistent"
            summary: "Some of Alertmanager members are not members the cluster."
            description: "Alertmanager has not found all other members of the cluster."
