apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kube-state-metrics-alert-rules
  labels:
    prometheus: visibility
    role: alert-rules
spec:
  groups:
    - name: alert--kube-state-metrics
      rules:
        - alert: KubeStateMetricsListErrors
          expr: |
            (sum(rate(kube_state_metrics_list_total{job="kube-state-metrics",result="error"}[5m]))
              /
            sum(rate(kube_state_metrics_list_total{job="kube-state-metrics"}[5m])))
            > 0.01
          for: 15m
          labels:
            severity: critical
            team: visibility
            service: kube-state-metrics
          annotations:
            title: "kube-state-metrics is experiencing errors in list operations"
            summary: "Thes kube-state-metrics is experiencing errors at an elevated rate in list operations"
            description: kube-state-metrics is experiencing errors at an elevated rate in list operations. This is likely causing it to not be able to expose metrics about Kubernetes objects correctly or at all.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubestatemetricslisterrors
        - alert: KubeStateMetricsWatchErrors
          expr: |
            (sum(rate(kube_state_metrics_watch_total{job="kube-state-metrics",result="error"}[5m]))
              /
            sum(rate(kube_state_metrics_watch_total{job="kube-state-metrics"}[5m])))
            > 0.01
          for: 15m
          labels:
            severity: critical
            team: visibility
            service: kube-state-metrics
          annotations:
            title: "kube-state-metrics is experiencing errors in watch operations"
            summary: "Thes kube-state-metrics is experiencing errors at an elevated rate in watch operations"
            description: kube-state-metrics is experiencing errors at an elevated rate in watch operations. This is likely causing it to not be able to expose metrics about Kubernetes objects correctly or at all.
            runbook_url: https://github.com/kubernetes-monitoring/kubernetes-mixin/tree/master/runbook.md#alert-name-kubestatemetricswatcherrors
