apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: prometheus-operator-alert-rules
  labels:
    prometheus: visibility
    role: alert-rules
spec:
  groups:
    - name: alert--prometheus-operator
      rules:
        - alert: PrometheusOperatorReconcileErrors
          expr: |
            rate(prometheus_operator_reconcile_errors_total{job="prometheus-operator"}[5m]) > 0.1
          for: 10m
          labels:
            severity: warning
            team: visibility
            service: prometheus-operator
          annotations:
            title: "prometheus-operator reconcile errors"
            summary: "The prometheus-operator is experiencing errors while reconciling prometheus"
            description: "Errors while reconciling {{ $labels.controller }} in {{ $labels.namespace }} Namespace."
        - alert: PrometheusOperatorNodeLookupErrors
          expr: |
            rate(prometheus_operator_node_address_lookup_errors_total{job="prometheus-operator"}[5m]) > 0.1
          for: 10m
          labels:
            severity: warning
            team: visibility
            service: prometheus-operator
          annotations:
            title: "prometheus-operator node lookup errors"
            summary: "The prometheus-operator is experiencing nodes lookup errors while reconciling prometheus"
            description: "Nodes lookup errors while reconciling Prometheus in {{ $labels.namespace }} Namespace."
