apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus-operator
spec:
  template:
    spec:
      containers:
        - name: prometheus-operator
          resources:
            limits:
              cpu: 300m # kpt-set: ${prometheus-operator.resources-limits-cpu}
              memory: 300Mi # kpt-set: ${prometheus-operator.resources-limits-memory}
            requests:
              cpu: 100m # kpt-set: ${prometheus-operator.resources-requests-cpu}
              memory: 100Mi # kpt-set: ${prometheus-operator.resources-requests-memory}
