apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-operator
  labels:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: prometheus-operator
    prometheus-visibility.monitoring: "enabled"
spec:
  jobLabel: prometheus-operator
  selector:
    matchLabels:
      app.kubernetes.io/component: controller
      app.kubernetes.io/name: prometheus-operator
  namespaceSelector:
    matchNames:
      - kube-visibility # kpt-set: ${namespace}
  endpoints:
    - honorLabels: true
      port: http
