apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: prometheus-visibility
  labels:
    name: prometheus-visibility
    prometheus-visibility.monitoring: "enabled"
spec:
  jobLabel: prometheus
  selector:
    matchLabels:
      prometheus: visibility
  namespaceSelector:
    matchNames:
      - kube-visibility # kpt-set: ${namespace}
  endpoints:
    - interval: 30s
      port: web
