apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: kube-state-metrics
  name: kube-state-metrics
  namespace: kube-system
spec:
  replicas: 1 # kpt-set: ${kube-state-metrics.replicas}
  template:
    spec:
      containers:
        - name: kube-state-metrics
          resources:
            limits:
              cpu: 100m # kpt-set: ${kube-state-metrics.resources-limits-cpu}
              memory: 100Mi # kpt-set: ${kube-state-metrics.resources-limits-memory}
            requests:
              cpu: 50m # kpt-set: ${kube-state-metrics.resources-requests-cpu}
              memory: 50Mi # kpt-set: ${kube-state-metrics.resources-requests-memory}
