apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: visibility
  labels:
    prometheus: visibility
spec:
  replicas: 1
  version: v2.27.1
  image: quay.io/prometheus/prometheus
  serviceAccountName: prometheus-visibility
  enableAdminAPI: true
  portName: web
  logLevel: info
  logFormat: logfmt
  resources:
    requests:
      memory: 100Mi
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  nodeSelector:
    kubernetes.io/os: linux
