apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBindingList
metadata:
  name: role-binding-namespaces
items:
  - apiVersion: rbac.authorization.k8s.io/v1
    kind: RoleBinding
    metadata:
      name: prometheus-visibility
      namespace: kube-visibility
    roleRef:
      apiGroup: rbac.authorization.k8s.io
      kind: Role
      name: prometheus-visibility
    subjects:
      - kind: ServiceAccount
        name: prometheus-visibility
