apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: node-exporter
  labels:
    k8s-app: node-exporter
    prometheus-visibility.monitoring: "enabled"
spec:
  jobLabel: node-exporter
  selector:
    matchLabels:
      k8s-app: node-exporter
  namespaceSelector:
    matchNames:
      - kube-visibility # kpt-set: ${namespace}
  endpoints:
    - port: https
      scheme: https
      interval: 30s
      bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
      tlsConfig:
        insecureSkipVerify: true
      relabelings:
        - action: replace
          regex: (.*)
          replacement: $1
          sourceLabels:
            - __meta_kubernetes_pod_node_name
          targetLabel: instance
