apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.metrics.k8s.io
spec:
  version: v1beta1
  service:
    name: prometheus-adapter
    namespace: kube-visibility # kpt-set: ${namespace}
  group: metrics.k8s.io
  groupPriorityMinimum: 100
  insecureSkipTLSVerify: true
  versionPriority: 100
